---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant # provide a default test-kitchen driver, vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  client_rb:
    environment: _default

platforms:
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04
    run_list:
    - recipe[apt]
    - recipe[curl]
    - recipe[elasticsearch_test::fix_cacerts]
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
    run_list:
    - recipe[apt]
    - recipe[curl]
    - recipe[elasticsearch_test::fix_cacerts]
  - name: centos-8
    driver:
      box: bento/centos-8
    run_list:
    - recipe[yum]
    - recipe[curl]
  - name: centos-7
    driver:
      box: bento/centos-7
    run_list:
    - recipe[yum]
    - recipe[curl]

suites:
  - name: repository # install from repository
    run_list:
      - recipe[elasticsearch_test::default_with_plugins]
    attributes:
      elasticsearch:
        install:
          type: repository

  - name: tarball # install by tarball
    run_list:
      - recipe[elasticsearch_test::default_with_plugins]
    attributes:
      elasticsearch:
        install:
          type: tarball

  - name: package # install from package directly
    run_list:
      - recipe[elasticsearch_test::default_with_plugins]
    attributes:
      elasticsearch:
        install:
          type: package

  - name: doubleinstance
    run_list:
      - recipe[elasticsearch_test::doubleinstances]

  - name: override_package # the override-everything use case
    run_list:
      - recipe[elasticsearch_test::package]

  - name: override_tarball # the override-everything use case
    run_list:
      - recipe[elasticsearch_test::tarball]
